---
- name: start service
  service: 
    name: "{{ service_name }}"
    state: started
  listen: "start service"

- name: restart service
  service:
    name: "{{ service_name }}"
    state: restarted
  listen: "restart service"

- name: stop service
  service:
    name: "{{ service_name }}"
    state: stopped
  listen: "stop service"
